import type { FastifyPluginAsync } from 'fastify';

/**
 * OpenAPI 3.0 Specification for SGI 360 2FA and Admin APIs
 *
 * This plugin configures comprehensive API documentation including:
 * - Authentication endpoints
 * - 2FA management endpoints
 * - Admin panel endpoints
 * - Audit logging endpoints
 */

export const openApiPlugin: FastifyPluginAsync = async (app) => {
  // OpenAPI spec is automatically generated by @fastify/swagger
  // based on route definitions and schema decorations
  // This plugin ensures proper configuration

  app.log.info('OpenAPI specification configured');
};

export const openApiSpec = {
  openapi: '3.0.0',
  info: {
    title: 'SGI 360 API - 2FA & Admin Management',
    version: '1.0.0',
    description: 'Production-ready API for Two-Factor Authentication and Admin Panel Management',
    contact: {
      name: 'SGI 360 Support',
      email: 'support@sgi360.com',
    },
    license: {
      name: 'MIT',
    },
  },
  servers: [
    {
      url: 'http://localhost:3001',
      description: 'Development server',
    },
    {
      url: 'https://api.sgi360.com',
      description: 'Production server',
    },
  ],
  security: [
    {
      bearerAuth: [],
    },
    {
      cookieAuth: [],
    },
  ],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      },
      cookieAuth: {
        type: 'apiKey',
        in: 'cookie',
        name: 'auth_token',
      },
    },
    schemas: {
      // ── Common Schemas ──
      Error: {
        type: 'object',
        required: ['error'],
        properties: {
          error: {
            type: 'string',
            description: 'Error message',
          },
          code: {
            type: 'string',
            description: 'Error code for machine processing',
          },
          issues: {
            type: 'array',
            description: 'Validation issues (for validation errors)',
            items: {
              type: 'object',
              properties: {
                path: {
                  type: 'string',
                },
                message: {
                  type: 'string',
                },
              },
            },
          },
        },
      },

      // ── Authentication Schemas ──
      LoginRequest: {
        type: 'object',
        required: ['email', 'password'],
        properties: {
          email: {
            type: 'string',
            format: 'email',
            description: 'User email address',
          },
          password: {
            type: 'string',
            format: 'password',
            description: 'User password',
            minLength: 8,
          },
        },
      },

      LoginResponse: {
        type: 'object',
        required: ['success', 'token'],
        properties: {
          success: {
            type: 'boolean',
          },
          token: {
            type: 'string',
            description: 'JWT authentication token',
          },
          requires2FA: {
            type: 'boolean',
            description: 'Whether 2FA verification is required',
          },
          sessionToken: {
            type: 'string',
            description: 'Temporary session token for 2FA verification',
          },
        },
      },

      // ── 2FA Schemas ──
      TwoFactorSetupResponse: {
        type: 'object',
        required: ['secret', 'qrCodeUrl', 'manualEntryKey'],
        properties: {
          secret: {
            type: 'string',
            description: 'TOTP secret key (base32 encoded)',
          },
          qrCodeUrl: {
            type: 'string',
            description: 'Data URL for QR code image',
          },
          manualEntryKey: {
            type: 'string',
            description: 'Manual entry key for authenticator app',
          },
          message: {
            type: 'string',
          },
        },
      },

      TwoFactorConfirmRequest: {
        type: 'object',
        required: ['token'],
        properties: {
          token: {
            type: 'string',
            pattern: '^\\d{6}$',
            description: '6-digit TOTP token',
          },
        },
      },

      TwoFactorConfirmResponse: {
        type: 'object',
        required: ['success', 'recoveryCodes'],
        properties: {
          success: {
            type: 'boolean',
          },
          message: {
            type: 'string',
          },
          recoveryCodes: {
            type: 'array',
            items: {
              type: 'string',
            },
            description: 'One-time backup recovery codes',
          },
          recoveryCodesMessage: {
            type: 'string',
          },
        },
      },

      TwoFactorStatus: {
        type: 'object',
        required: ['enabled', 'lastVerified'],
        properties: {
          enabled: {
            type: 'boolean',
            description: 'Whether 2FA is enabled for user',
          },
          lastVerified: {
            type: 'string',
            format: 'date-time',
            description: 'Last time 2FA was verified',
          },
          method: {
            type: 'string',
            enum: ['TOTP', 'SMS', 'EMAIL'],
            description: '2FA method used',
          },
          backupCodesRemaining: {
            type: 'integer',
            description: 'Number of unused backup codes',
          },
        },
      },

      TwoFactorDisableRequest: {
        type: 'object',
        required: ['password'],
        properties: {
          password: {
            type: 'string',
            format: 'password',
            description: 'User password for confirmation',
          },
        },
      },

      TwoFactorVerifyRequest: {
        type: 'object',
        required: ['sessionToken', 'token'],
        properties: {
          sessionToken: {
            type: 'string',
            description: 'Temporary session token from login',
          },
          token: {
            type: 'string',
            description: '6-digit TOTP code or recovery code',
            minLength: 6,
          },
        },
      },

      RecoveryCodes: {
        type: 'object',
        required: ['total', 'unused', 'used'],
        properties: {
          total: {
            type: 'integer',
          },
          unused: {
            type: 'integer',
          },
          used: {
            type: 'integer',
          },
          codes: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                },
                used: {
                  type: 'boolean',
                },
                usedAt: {
                  type: 'string',
                  format: 'date-time',
                },
                usedBy: {
                  type: 'string',
                },
              },
            },
          },
        },
      },

      // ── Admin Schemas ──
      AdminUser2FAStatus: {
        type: 'object',
        properties: {
          userId: {
            type: 'string',
          },
          email: {
            type: 'string',
          },
          name: {
            type: 'string',
          },
          twoFactorEnabled: {
            type: 'boolean',
          },
          lastVerified: {
            type: 'string',
            format: 'date-time',
          },
          recoveryCodesCount: {
            type: 'integer',
          },
          createdAt: {
            type: 'string',
            format: 'date-time',
          },
        },
      },

      AdminUsersList: {
        type: 'object',
        required: ['users', 'total', 'page', 'pageSize'],
        properties: {
          users: {
            type: 'array',
            items: {
              $ref: '#/components/schemas/AdminUser2FAStatus',
            },
          },
          total: {
            type: 'integer',
          },
          page: {
            type: 'integer',
          },
          pageSize: {
            type: 'integer',
          },
        },
      },

      AuditLogEntry: {
        type: 'object',
        required: ['id', 'userId', 'action', 'timestamp'],
        properties: {
          id: {
            type: 'string',
          },
          userId: {
            type: 'string',
          },
          action: {
            type: 'string',
            enum: [
              '2FA_ENABLED',
              '2FA_DISABLED',
              '2FA_VERIFIED',
              '2FA_RECOVERY_USED',
              'LOGIN_SUCCESS',
              'LOGIN_FAILED',
              'PASSWORD_CHANGED',
              'RECOVERY_CODES_REGENERATED',
            ],
          },
          ipAddress: {
            type: 'string',
          },
          userAgent: {
            type: 'string',
          },
          timestamp: {
            type: 'string',
            format: 'date-time',
          },
          details: {
            type: 'object',
            additionalProperties: true,
          },
        },
      },

      AlertRequest: {
        type: 'object',
        required: ['subject', 'message'],
        properties: {
          subject: {
            type: 'string',
            description: 'Alert subject',
          },
          message: {
            type: 'string',
            description: 'Alert message',
          },
          type: {
            type: 'string',
            enum: ['INFO', 'WARNING', 'CRITICAL'],
            default: 'INFO',
          },
        },
      },
    },
  },
  paths: {
    // ── Authentication Endpoints ──
    '/auth/login': {
      post: {
        tags: ['Authentication'],
        summary: 'User login',
        description: 'Authenticate user with email and password. Returns JWT token or requires 2FA verification.',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/LoginRequest',
              },
            },
          },
        },
        responses: {
          200: {
            description: 'Login successful',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/LoginResponse',
                },
              },
            },
          },
          401: {
            description: 'Invalid credentials',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
              },
            },
          },
          400: {
            description: 'Validation error',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
              },
            },
          },
        },
      },
    },

    // ── 2FA Endpoints ──
    '/2fa/setup': {
      post: {
        tags: ['Two-Factor Authentication'],
        summary: 'Start 2FA setup',
        description: 'Generate TOTP secret and QR code for authenticator app',
        security: [{ bearerAuth: [] }],
        responses: {
          200: {
            description: 'Setup initialized',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/TwoFactorSetupResponse',
                },
              },
            },
          },
          401: {
            description: 'Unauthorized',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
              },
            },
          },
        },
      },
    },

    '/2fa/confirm': {
      post: {
        tags: ['Two-Factor Authentication'],
        summary: 'Confirm 2FA setup',
        description: 'Verify TOTP token to complete 2FA setup and receive recovery codes',
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/TwoFactorConfirmRequest',
              },
            },
          },
        },
        responses: {
          200: {
            description: '2FA confirmed and enabled',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/TwoFactorConfirmResponse',
                },
              },
            },
          },
          400: {
            description: 'Invalid TOTP token',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
              },
            },
          },
          401: {
            description: 'Unauthorized',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
              },
            },
          },
        },
      },
    },

    '/2fa/verify': {
      post: {
        tags: ['Two-Factor Authentication'],
        summary: 'Verify 2FA during login',
        description: 'Verify TOTP code or recovery code during login process',
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/TwoFactorVerifyRequest',
              },
            },
          },
        },
        responses: {
          200: {
            description: '2FA verification successful',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    success: { type: 'boolean' },
                    message: { type: 'string' },
                  },
                },
              },
            },
          },
          401: {
            description: 'Invalid token or recovery code',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
              },
            },
          },
        },
      },
    },

    '/2fa/disable': {
      post: {
        tags: ['Two-Factor Authentication'],
        summary: 'Disable 2FA',
        description: 'Disable 2FA for authenticated user (requires password confirmation)',
        security: [{ bearerAuth: [] }],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/TwoFactorDisableRequest',
              },
            },
          },
        },
        responses: {
          200: {
            description: '2FA disabled',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    success: { type: 'boolean' },
                    message: { type: 'string' },
                  },
                },
              },
            },
          },
          401: {
            description: 'Invalid password or unauthorized',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
              },
            },
          },
        },
      },
    },

    '/2fa/status': {
      get: {
        tags: ['Two-Factor Authentication'],
        summary: 'Get 2FA status',
        description: 'Get current 2FA status for authenticated user',
        security: [{ bearerAuth: [] }],
        responses: {
          200: {
            description: '2FA status retrieved',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    status: {
                      $ref: '#/components/schemas/TwoFactorStatus',
                    },
                  },
                },
              },
            },
          },
          401: {
            description: 'Unauthorized',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
              },
            },
          },
        },
      },
    },

    '/2fa/recovery-codes': {
      get: {
        tags: ['Two-Factor Authentication'],
        summary: 'Get recovery codes info',
        description: 'Get status and count of recovery codes',
        security: [{ bearerAuth: [] }],
        responses: {
          200: {
            description: 'Recovery codes info',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/RecoveryCodes',
                },
              },
            },
          },
          401: {
            description: 'Unauthorized',
          },
        },
      },
      post: {
        tags: ['Two-Factor Authentication'],
        summary: 'Regenerate recovery codes',
        description: 'Generate new set of recovery codes for 2FA',
        security: [{ bearerAuth: [] }],
        responses: {
          200: {
            description: 'New recovery codes generated',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    success: { type: 'boolean' },
                    recoveryCodes: {
                      type: 'array',
                      items: { type: 'string' },
                    },
                    message: { type: 'string' },
                  },
                },
              },
            },
          },
          401: {
            description: 'Unauthorized',
          },
        },
      },
    },

    // ── Admin Endpoints ──
    '/admin/2fa/users': {
      get: {
        tags: ['Admin - 2FA Management'],
        summary: 'List all users with 2FA status',
        description: 'Get paginated list of all users with their 2FA status (admin only)',
        security: [{ bearerAuth: [] }],
        parameters: [
          {
            name: 'page',
            in: 'query',
            schema: { type: 'integer', default: 1 },
          },
          {
            name: 'pageSize',
            in: 'query',
            schema: { type: 'integer', default: 20 },
          },
          {
            name: 'search',
            in: 'query',
            schema: { type: 'string' },
            description: 'Search by email or name',
          },
          {
            name: '2faEnabled',
            in: 'query',
            schema: { type: 'boolean' },
            description: 'Filter by 2FA status',
          },
        ],
        responses: {
          200: {
            description: 'Users list with 2FA status',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/AdminUsersList',
                },
              },
            },
          },
          403: {
            description: 'Admin access required',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Error',
                },
              },
            },
          },
        },
      },
    },

    '/admin/2fa/users/{userId}/audit-logs': {
      get: {
        tags: ['Admin - Audit Logs'],
        summary: 'Get user audit logs',
        description: 'Get audit trail for specific user (admin only)',
        security: [{ bearerAuth: [] }],
        parameters: [
          {
            name: 'userId',
            in: 'path',
            required: true,
            schema: { type: 'string' },
          },
          {
            name: 'limit',
            in: 'query',
            schema: { type: 'integer', default: 50 },
          },
          {
            name: 'offset',
            in: 'query',
            schema: { type: 'integer', default: 0 },
          },
        ],
        responses: {
          200: {
            description: 'Audit logs for user',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    logs: {
                      type: 'array',
                      items: {
                        $ref: '#/components/schemas/AuditLogEntry',
                      },
                    },
                    total: { type: 'integer' },
                  },
                },
              },
            },
          },
          403: {
            description: 'Admin access required',
          },
          404: {
            description: 'User not found',
          },
        },
      },
    },

    '/admin/2fa/users/{userId}/disable': {
      post: {
        tags: ['Admin - 2FA Management'],
        summary: 'Disable user 2FA (admin override)',
        description: 'Admin override to disable 2FA for a user',
        security: [{ bearerAuth: [] }],
        parameters: [
          {
            name: 'userId',
            in: 'path',
            required: true,
            schema: { type: 'string' },
          },
        ],
        responses: {
          200: {
            description: '2FA disabled for user',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    success: { type: 'boolean' },
                    message: { type: 'string' },
                  },
                },
              },
            },
          },
          403: {
            description: 'Admin access required',
          },
          404: {
            description: 'User not found',
          },
        },
      },
    },

    '/admin/2fa/users/{userId}/alert': {
      post: {
        tags: ['Admin - Security Alerts'],
        summary: 'Send security alert to user',
        description: 'Send security alert or notification to specific user',
        security: [{ bearerAuth: [] }],
        parameters: [
          {
            name: 'userId',
            in: 'path',
            required: true,
            schema: { type: 'string' },
          },
        ],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                $ref: '#/components/schemas/AlertRequest',
              },
            },
          },
        },
        responses: {
          200: {
            description: 'Alert sent successfully',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    success: { type: 'boolean' },
                    message: { type: 'string' },
                  },
                },
              },
            },
          },
          403: {
            description: 'Admin access required',
          },
          404: {
            description: 'User not found',
          },
        },
      },
    },

    // ── Audit Logs (User & Admin) ──
    '/audit-logs': {
      get: {
        tags: ['Audit Logs'],
        summary: 'Get user audit logs',
        description: 'Get audit logs for current authenticated user',
        security: [{ bearerAuth: [] }],
        parameters: [
          {
            name: 'limit',
            in: 'query',
            schema: { type: 'integer', default: 50 },
          },
          {
            name: 'offset',
            in: 'query',
            schema: { type: 'integer', default: 0 },
          },
        ],
        responses: {
          200: {
            description: 'User audit logs',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    logs: {
                      type: 'array',
                      items: {
                        $ref: '#/components/schemas/AuditLogEntry',
                      },
                    },
                    total: { type: 'integer' },
                  },
                },
              },
            },
          },
          401: {
            description: 'Unauthorized',
          },
        },
      },
    },
  },
};
