CREATE DATABASE IF NOT EXISTS sgi OWNER postgres;
\c sgi
GRANT ALL PRIVILEGES ON DATABASE sgi TO postgres WITH GRANT OPTION;
ALTER SCHEMA public OWNER TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA public TO postgres WITH GRANT OPTION;
