import { FastifyInstance } from 'fastify';

// Servicio de generación automática de proyectos
export class Project360AutoGeneration {
  constructor(private app: FastifyInstance) {}

  // Evento: Auditoría con No Conformidad
  async handleAuditFinding(auditId: string, findingId: string, severity: string) {
    try {
      // Obtener información del hallazgo
      const finding = await this.app.prisma.auditFinding.findUnique({
        where: { id: findingId },
        include: {
          audit: {
            select: { id: true, code: true, tenantId: true }
          }
        }
      });

      if (!finding) return;

      // Determinar responsable basado en el área del hallazgo
      const responsibleId = await this.determineResponsible(finding.audit.tenantId, finding.area);

      // Calcular fecha objetivo basada en severidad
      const targetDate = this.calculateTargetDate(severity);

      // Generar proyecto
      await this.app.prisma.actionProject.create({
        data: {
          code: await this.generateProjectCode(finding.audit.tenantId),
          name: `Plan de Acción - Hallazgo Auditoría: ${finding.title}`,
          description: `Plan de acción para corregir hallazgo de auditoría: ${finding.description}`,
          origin: 'AUDIT_FINDING',
          originModule: 'auditorias',
          originEntityId: findingId,
          originReference: `AUD-${finding.audit.id}-FIND-${findingId}`,
          tenantId: finding.audit.tenantId,
          responsibleId,
          targetDate,
          status: 'PENDING',
          priority: this.mapSeverityToPriority(severity),
          impactLevel: this.mapSeverityToImpact(severity),
          createdBy: finding.audit.createdById || 'system',
          metadata: {
            auditId: finding.audit.id,
            findingId: findingId,
            severity,
            autoGenerated: true,
            generatedAt: new Date().toISOString()
          }
        }
      });

      console.log(`✅ Proyecto generado automáticamente desde hallazgo de auditoría: ${findingId}`);
    } catch (error) {
      console.error('Error generando proyecto desde hallazgo de auditoría:', error);
    }
  }

  // Evento: Incidente registrado
  async handleIncident(incidentId: string) {
    try {
      const incident = await this.app.prisma.incident.findUnique({
        where: { id: incidentId },
        include: {
          reporter: {
            select: { id: true, firstName: true, lastName: true }
          }
        }
      });

      if (!incident) return;

      const responsibleId = await this.determineResponsible(incident.tenantId, incident.area);
      const targetDate = this.calculateTargetDate(incident.severity);

      await this.app.prisma.actionProject.create({
        data: {
          code: await this.generateProjectCode(incident.tenantId),
          name: `Plan de Acción - Incidente: ${incident.title}`,
          description: `Plan de acción para investigar y resolver incidente: ${incident.description}`,
          origin: 'INCIDENT',
          originModule: 'incidents',
          originEntityId: incidentId,
          originReference: `INC-${incidentId}`,
          tenantId: incident.tenantId,
          responsibleId,
          targetDate,
          status: 'PENDING',
          priority: this.mapSeverityToPriority(incident.severity),
          impactLevel: this.mapSeverityToImpact(incident.severity),
          createdBy: incident.reporterId || 'system',
          metadata: {
            incidentId,
            severity: incident.severity,
            autoGenerated: true,
            generatedAt: new Date().toISOString()
          }
        }
      });

      console.log(`✅ Proyecto generado automáticamente desde incidente: ${incidentId}`);
    } catch (error) {
      console.error('Error generando proyecto desde incidente:', error);
    }
  }

  // Evento: Desvío en simulacro
  async handleDrillDeviation(drillId: string, deviationId: string) {
    try {
      const drill = await this.app.prisma.drillScenario.findUnique({
        where: { id: drillId },
        include: {
          coordinator: {
            select: { id: true, firstName: true, lastName: true }
          }
        }
      });

      if (!drill) return;

      // Obtener información del desvío
      const deviation = await this.app.prisma.drillDeviation.findUnique({
        where: { id: deviationId }
      });

      if (!deviation) return;

      const responsibleId = await this.determineResponsible(drill.tenantId, drill.coordinatorId);
      const targetDate = this.calculateTargetDate(deviation.severity);

      await this.app.prisma.actionProject.create({
        data: {
          code: await this.generateProjectCode(drill.tenantId),
          name: `Plan de Mejora - Desvío Simulacro: ${drill.name}`,
          description: `Plan de acción para corregir desvío detectado en simulacro: ${deviation.description}`,
          origin: 'DRILL_DEVIATION',
          originModule: 'simulacros',
          originEntityId: deviationId,
          originReference: `DRILL-${drillId}-DEV-${deviationId}`,
          tenantId: drill.tenantId,
          responsibleId,
          targetDate,
          status: 'PENDING',
          priority: this.mapSeverityToPriority(deviation.severity),
          impactLevel: this.mapSeverityToImpact(deviation.severity),
          createdBy: drill.coordinatorId,
          metadata: {
            drillId,
            deviationId,
            severity: deviation.severity,
            autoGenerated: true,
            generatedAt: new Date().toISOString()
          }
        }
      });

      console.log(`✅ Proyecto generado automáticamente desde desvío de simulacro: ${deviationId}`);
    } catch (error) {
      console.error('Error generando proyecto desde desvío de simulacro:', error);
    }
  }

  // Evento: Problema de mantenimiento
  async handleMaintenanceIssue(workOrderId: string) {
    try {
      const workOrder = await this.app.prisma.workOrder.findUnique({
        where: { id: workOrderId },
        include: {
          technician: {
            select: { id: true, firstName: true, lastName: true }
          }
        }
      });

      if (!workOrder) return;

      // Solo generar proyectos para problemas críticos o recurrentes
      if (workOrder.priority !== 'CRITICAL' && workOrder.type !== 'EMERGENCY') {
        return;
      }

      const responsibleId = await this.determineResponsible(workOrder.tenantId, 'mantenimiento');
      const targetDate = this.calculateTargetDate('HIGH');

      await this.app.prisma.actionProject.create({
        data: {
          code: await this.generateProjectCode(workOrder.tenantId),
          name: `Plan de Acción - Problema Mantenimiento: ${workOrder.title}`,
          description: `Plan de acción para prevenir problemas recurrentes de mantenimiento: ${workOrder.description}`,
          origin: 'MAINTENANCE_ISSUE',
          originModule: 'mantenimiento',
          originEntityId: workOrderId,
          originReference: `WO-${workOrderId}`,
          tenantId: workOrder.tenantId,
          responsibleId,
          targetDate,
          status: 'PENDING',
          priority: 'HIGH',
          impactLevel: 'HIGH',
          createdBy: workOrder.technicianId || 'system',
          metadata: {
            workOrderId,
            workOrderType: workOrder.type,
            autoGenerated: true,
            generatedAt: new Date().toISOString()
          }
        }
      });

      console.log(`✅ Proyecto generado automáticamente desde problema de mantenimiento: ${workOrderId}`);
    } catch (error) {
      console.error('Error generando proyecto desde problema de mantenimiento:', error);
    }
  }

  // Evento: Riesgo crítico detectado
  async handleCriticalRisk(riskId: string) {
    try {
      const risk = await this.app.prisma.risk.findUnique({
        where: { id: riskId },
        include: {
          owner: {
            select: { id: true, firstName: true, lastName: true }
          }
        }
      });

      if (!risk || risk.status !== 'CRITICAL') return;

      const responsibleId = risk.ownerId;
      const targetDate = this.calculateTargetDate('CRITICAL');

      await this.app.prisma.actionProject.create({
        data: {
          code: await this.generateProjectCode(risk.tenantId),
          name: `Plan de Mitigación - Riesgo Crítico: ${risk.title}`,
          description: `Plan de acción para mitigar riesgo crítico identificado: ${risk.description}`,
          origin: 'RISK_DETECTED',
          originModule: 'riesgos',
          originEntityId: riskId,
          originReference: `RISK-${riskId}`,
          tenantId: risk.tenantId,
          responsibleId,
          targetDate,
          status: 'PENDING',
          priority: 'CRITICAL',
          impactLevel: 'CRITICAL',
          createdBy: risk.ownerId,
          metadata: {
            riskId,
            riskStatus: risk.status,
            probability: risk.probability,
            autoGenerated: true,
            generatedAt: new Date().toISOString()
          }
        }
      });

      console.log(`✅ Proyecto generado automáticamente desde riesgo crítico: ${riskId}`);
    } catch (error) {
      console.error('Error generando proyecto desde riesgo crítico:', error);
    }
  }

  // Helper functions
  private async generateProjectCode(tenantId: string): Promise<string> {
    const year = new Date().getFullYear();
    const projectCount = await this.app.prisma.actionProject.count({
      where: {
        tenantId,
        createdAt: {
          gte: new Date(`${year}-01-01`)
        }
      }
    });
    
    return `PROJ-${year}-${String(projectCount + 1).padStart(3, '0')}`;
  }

  private async determineResponsible(tenantId: string, area: string): Promise<string> {
    // Lógica para determinar responsable basado en área y tenant
    // Esto podría basarse en roles, departamentos, etc.
    
    const defaultResponsible = await this.app.prisma.platformUser.findFirst({
      where: {
        tenantId,
        globalRole: 'SUPER_ADMIN'
      }
    });

    return defaultResponsible?.id || 'system';
  }

  private calculateTargetDate(severity: string): Date {
    const now = new Date();
    const daysToAdd: Record<string, number> = {
      'LOW': 30,
      'MEDIUM': 21,
      'HIGH': 14,
      'CRITICAL': 7
    };

    const days = daysToAdd[severity] || 21;
    const targetDate = new Date(now);
    targetDate.setDate(targetDate.getDate() + days);

    return targetDate;
  }

  private mapSeverityToPriority(severity: string): string {
    const mapping: Record<string, string> = {
      'LOW': 'LOW',
      'MEDIUM': 'MEDIUM',
      'HIGH': 'HIGH',
      'CRITICAL': 'CRITICAL'
    };

    return mapping[severity] || 'MEDIUM';
  }

  private mapSeverityToImpact(severity: string): string {
    const mapping: Record<string, string> = {
      'LOW': 'LOW',
      'MEDIUM': 'MEDIUM',
      'HIGH': 'HIGH',
      'CRITICAL': 'CRITICAL'
    };

    return mapping[severity] || 'MEDIUM';
  }
}
